export const ICON_LIST = [
  {
    name: 'SearchIcon',
    keywords: ['find', 'scan', 'magnifier', 'magnifying glass'],
    icon: defineAsyncComponent(() => import('./SearchIcon.vue')),
    raw: () => import('./SearchIcon.vue?raw'),
  },
  {
    name: 'CartIcon',
    keywords: ['trolley', 'cart', 'basket', 'e-commerce', 'store', 'purchase', 'products', 'items', 'ingredients'],
    icon: defineAsyncComponent(() => import('./CartIcon.vue')),
    raw: () => import('./CartIcon.vue?raw'),
  },
  {
    name: 'LayersIcon',
    keywords: ['stack', 'pile', 'pages', 'sheets', 'paperwork', 'copies', 'copy'],
    icon: defineAsyncComponent(() => import('./LayersIcon.vue')),
    raw: () => import('./LayersIcon.vue?raw'),
  },
  {
    name: 'GripIcon',
    keywords: ['grab', 'dots', 'handle', 'move', 'drag'],
    icon: defineAsyncComponent(() => import('./GripIcon.vue')),
    raw: () => import('./GripIcon.vue?raw'),
  },
  {
    name: 'FrameIcon',
    keywords: ['logo', 'design', 'tool'],
    icon: defineAsyncComponent(() => import('./FrameIcon.vue')),
    raw: () => import('./FrameIcon.vue?raw'),
  },
  {
    name: 'SunIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./SunIcon.vue')),
    raw: () => import('./SunIcon.vue?raw'),
  },
  {
    name: 'DeleteIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./DeleteIcon.vue')),
    raw: () => import('./DeleteIcon.vue?raw'),
  },
  {
    name: 'FileStackIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./FileStackIcon.vue')),
    raw: () => import('./FileStackIcon.vue?raw'),
  },
  {
    name: 'SettingGearIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./SettingGearIcon.vue')),
    raw: () => import('./SettingGearIcon.vue?raw'),
  },
  {
    name: 'CalendarCogIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./CalendarCogIcon.vue')),
    raw: () => import('./CalendarCogIcon.vue?raw'),
  },
  {
    name: 'MenuIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./MenuIcon.vue')),
    raw: () => import('./MenuIcon.vue?raw'),
  },
  {
    name: 'CopyIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./CopyIcon.vue')),
    raw: () => import('./CopyIcon.vue?raw'),
  },
  {
    name: 'AudioLinesIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./AudioLinesIcon.vue')),
    raw: () => import('./AudioLinesIcon.vue?raw'),
  },
  {
    name: 'ArchiveIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./ArchiveIcon.vue')),
    raw: () => import('./ArchiveIcon.vue?raw'),
  },
  {
    name: 'LogoutIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./LogoutIcon.vue')),
    raw: () => import('./LogoutIcon.vue?raw'),
  },
  {
    name: 'CircleHelpIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./CircleHelpIcon.vue')),
    raw: () => import('./CircleHelpIcon.vue?raw'),
  },
  {
    name: 'SquareStackIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./SquareStackIcon.vue')),
    raw: () => import('./SquareStackIcon.vue?raw'),
  },
  {
    name: 'MessageCircleIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./MessageCircleIcon.vue')),
    raw: () => import('./MessageCircleIcon.vue?raw'),
  },
  {
    name: 'MessageCircleMoreIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./MessageCircleMoreIcon.vue')),
    raw: () => import('./MessageCircleMoreIcon.vue?raw'),
  },
  {
    name: 'ArrowLeftIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./ArrowLeftIcon.vue')),
    raw: () => import('./ArrowLeftIcon.vue?raw'),
  },
  {
    name: 'ArrowRightIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./ArrowRightIcon.vue')),
    raw: () => import('./ArrowRightIcon.vue?raw'),
  },
  {
    name: 'RefreshIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./RefreshIcon.vue')),
    raw: () => import('./RefreshIcon.vue?raw'),
  },
  {
    name: 'DownloadIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./DownloadIcon.vue')),
    raw: () => import('./DownloadIcon.vue?raw'),
  },
  {
    name: 'SquarePenIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./SquarePenIcon.vue')),
    raw: () => import('./SquarePenIcon.vue?raw'),
  },
  {
    name: 'CursorClickIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./CursorClickIcon.vue')),
    raw: () => import('./CursorClickIcon.vue?raw'),
  },
  {
    name: 'ClockIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./ClockIcon.vue')),
    raw: () => import('./ClockIcon.vue?raw'),
  },
  {
    name: 'BadgeAlertIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./BadgeAlertIcon.vue')),
    raw: () => import('./BadgeAlertIcon.vue?raw'),
  },
  {
    name: 'BadgePercentIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./BadgePercentIcon.vue')),
    raw: () => import('./BadgePercentIcon.vue?raw'),
  },
  {
    name: 'ChartPieIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./ChartPieIcon.vue')),
    raw: () => import('./ChartPieIcon.vue?raw'),
  },
  {
    name: 'CompassIcon',
    keywords: ['direction', 'navigation', 'north', 'south', 'east', 'west', 'compass'],
    icon: defineAsyncComponent(() => import('./CompassIcon.vue')),
    raw: () => import('./CompassIcon.vue?raw'),
  },
  {
    name: 'TimerIcon',
    keywords: ['time', 'watch', 'alarm', 'stopwatch', 'stopwatch'],
    icon: defineAsyncComponent(() => import('./TimerIcon.vue')),
    raw: () => import('./TimerIcon.vue?raw'),
  },
  {
    name: 'ExpandIcon',
    keywords: ['scale', 'fullscreen'],
    icon: defineAsyncComponent(() => import('./ExpandIcon.vue')),
    raw: () => import('./ExpandIcon.vue?raw'),
  },
  {
    name: 'GaugeIcon',
    keywords: ['dashboard', 'dial', 'meter', 'speed', 'pressure', 'measure', 'level'],
    icon: defineAsyncComponent(() => import('./GaugeIcon.vue')),
    raw: () => import('./GaugeIcon.vue?raw'),
  },
  {
    name: 'BoneIcon',
    keywords: ['health', 'skeleton', 'skull', 'death', 'pets', 'dog'],
    icon: defineAsyncComponent(() => import('./BoneIcon.vue')),
    raw: () => import('./BoneIcon.vue?raw'),
  },
  {
    name: 'AlignCenterIcon',
    keywords: ['text', 'alignment', 'center'],
    icon: defineAsyncComponent(() => import('./AlignCenterIcon.vue')),
    raw: () => import('./AlignCenterIcon.vue?raw'),
  },
  {
    name: 'AlignHorizontalIcon',
    keywords: ['center', 'items', 'flex', 'justify', 'distribute', 'between'],
    icon: defineAsyncComponent(() => import('./AlignHorizontalIcon.vue')),
    raw: () => import('./AlignHorizontalIcon.vue?raw'),
  },
  {
    name: 'AlignVerticalIcon',
    keywords: ['center', 'items', 'flex', 'justify', 'distribute', 'between'],
    icon: defineAsyncComponent(() => import('./AlignVerticalIcon.vue')),
    raw: () => import('./AlignVerticalIcon.vue?raw'),
  },
  {
    name: 'BellIcon',
    keywords: ['alarm', 'notification', 'sound', 'reminder'],
    icon: defineAsyncComponent(() => import('./BellIcon.vue')),
    raw: () => import('./BellIcon.vue?raw'),
  },
  {
    name: 'UpvoteIcon',
    keywords: ['like', 'good', 'emotion'],
    icon: defineAsyncComponent(() => import('./UpvoteIcon.vue')),
    raw: () => import('./UpvoteIcon.vue?raw'),
  },
  {
    name: 'DownvoteIcon',
    keywords: ['dislike', 'bad', 'emotion'],
    icon: defineAsyncComponent(() => import('./DownvoteIcon.vue')),
    raw: () => import('./DownvoteIcon.vue?raw'),
  },
  {
    name: 'UserIcon',
    keywords: ['person', 'account', 'contact'],
    icon: defineAsyncComponent(() => import('./UserIcon.vue')),
    raw: () => import('./UserIcon.vue?raw'),
  },
  {
    name: 'UsersIcon',
    keywords: ['group', 'people'],
    icon: defineAsyncComponent(() => import('./UsersIcon.vue')),
    raw: () => import('./UsersIcon.vue?raw'),
  },
  {
    name: 'HandCoinsIcon',
    keywords: [
      'savings',
      'banking',
      'money',
      'finance',
      'offers',
      'mortgage',
      'payment',
      'received',
      'wage',
      'payroll',
      'allowance',
      'pocket money',
      'handout',
      'pennies',
    ],
    icon: defineAsyncComponent(() => import('./HandCoinsIcon.vue')),
    raw: () => import('./HandCoinsIcon.vue?raw'),
  },
  {
    name: 'CircleChevronUpIcon',
    keywords: ['caret', 'ahead', 'forward', 'menu', 'chevron'],
    icon: defineAsyncComponent(() => import('./CircleChevronUpIcon.vue')),
    raw: () => import('./CircleChevronUpIcon.vue?raw'),
  },
  {
    name: 'CircleChevronDownIcon',
    keywords: ['back', 'menu', 'chevron'],
    icon: defineAsyncComponent(() => import('./CircleChevronDownIcon.vue')),
    raw: () => import('./CircleChevronDownIcon.vue?raw'),
  },
  {
    name: 'CircleChevronLeftIcon',
    keywords: ['back', 'previous', 'less than', 'fewer', 'menu', '<', 'chevron'],
    icon: defineAsyncComponent(() => import('./CircleChevronLeftIcon.vue')),
    raw: () => import('./CircleChevronLeftIcon.vue?raw'),
  },
  {
    name: 'CircleChevronRightIcon',
    keywords: ['next', 'forward', 'more than', 'greater', 'menu', '>', 'chevron'],
    icon: defineAsyncComponent(() => import('./CircleChevronRightIcon.vue')),
    raw: () => import('./CircleChevronRightIcon.vue?raw'),
  },
  {
    name: 'ChevronsUpDownIcon',
    keywords: ['expand', 'unfold', 'vertical', 'chevron'],
    icon: defineAsyncComponent(() => import('./ChevronsUpDownIcon.vue')),
    raw: () => import('./ChevronsUpDownIcon.vue?raw'),
  },
  {
    name: 'ChevronsDownUpIcon',
    keywords: ['collapse', 'fold', 'vertical', 'chevron'],
    icon: defineAsyncComponent(() => import('./ChevronsDownUpIcon.vue')),
    raw: () => import('./ChevronsDownUpIcon.vue?raw'),
  },
  {
    name: 'ChevronsLeftRightIcon',
    keywords: ['expand', 'unfold', 'horizontal', 'chevron'],
    icon: defineAsyncComponent(() => import('./ChevronsLeftRightIcon.vue')),
    raw: () => import('./ChevronsLeftRightIcon.vue?raw'),
  },
  {
    name: 'ChevronsRightLeftIcon',
    keywords: ['collapse', 'fold', 'horizontal', 'chevron'],
    icon: defineAsyncComponent(() => import('./ChevronsRightLeftIcon.vue')),
    raw: () => import('./ChevronsRightLeftIcon.vue?raw'),
  },
  {
    name: 'CogIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./CogIcon.vue')),
    raw: () => import('./CogIcon.vue?raw'),
  },
  {
    name: 'RabbitIcon',
    keywords: [],
    icon: defineAsyncComponent(() => import('./RabbitIcon.vue')),
    raw: () => import('./RabbitIcon.vue?raw'),
  },
  {
    name: 'AlarmClockIcon',
    keywords: ['morning'],
    icon: defineAsyncComponent(() => import('./AlarmClockIcon.vue')),
    raw: () => import('./AlarmClockIcon.vue?raw'),
  },
  {
    name: 'LoaderPinwheelIcon',
    keywords: [
      'loading',
      'wait',
      'busy',
      'progress',
      'throbber',
      'spinner',
      'spinning',
      'beach ball',
      'frozen',
      'freeze',
    ],
    icon: defineAsyncComponent(() => import('./LoaderPinwheelIcon.vue')),
    raw: () => import('./LoaderPinwheelIcon.vue?raw'),
  },
  {
    name: 'PlayIcon',
    keywords: ['video', 'play', 'start'],
    icon: defineAsyncComponent(() => import('./PlayIcon.vue')),
    raw: () => import('./PlayIcon.vue?raw'),
  },
  {
    name: 'PauseIcon',
    keywords: ['video', 'pause', 'stop'],
    icon: defineAsyncComponent(() => import('./PauseIcon.vue')),
    raw: () => import('./PauseIcon.vue?raw'),
  },
  {
    name: 'ShowerHeadIcon',
    keywords: ['shower', 'bath', 'bathroom', 'amenities', 'services'],
    icon: defineAsyncComponent(() => import('./ShowerHeadIcon.vue')),
    raw: () => import('./ShowerHeadIcon.vue?raw'),
  },
  {
    name: 'TelescopeIcon',
    keywords: [
      'telescope',
      'astronomy',
      'space',
      'discovery',
      'exploration',
      'explore',
      'vision',
      'perspective',
      'focus',
      'stargazing',
      'observe',
      'view',
    ],
    icon: defineAsyncComponent(() => import('./TelescopeIcon.vue')),
    raw: () => import('./TelescopeIcon.vue?raw'),
  },
  {
    name: 'ClapIcon',
    keywords: [
      'clap',
      'movie',
      'film',
      'video',
      'camera',
      'cinema',
      'cut',
      'action',
      'television',
      'tv',
      'show',
      'entertainment',
    ],
    icon: defineAsyncComponent(() => import('./ClapIcon.vue')),
    raw: () => import('./ClapIcon.vue?raw'),
  },
  {
    name: 'WifiIcon',
    keywords: ['internet', 'electronic', 'connection', 'data'],
    icon: defineAsyncComponent(() => import('./WifiIcon.vue')),
    raw: () => import('./WifiIcon.vue?raw'),
  },
  {
    name: 'DrumIcon',
    keywords: ['music', 'instrument', 'percussion', 'beat', 'rhythm', 'sound'],
    icon: defineAsyncComponent(() => import('./DrumIcon.vue')),
    raw: () => import('./DrumIcon.vue?raw'),
  },
  {
    name: 'CctvIcon',
    keywords: ['cctv', 'camera', 'surveillance', 'recording', 'film', 'videotape', 'crime', 'watching'],
    icon: defineAsyncComponent(() => import('./CctvIcon.vue')),
    raw: () => import('./CctvIcon.vue?raw'),
  },
  {
    name: 'CoffeeIcon',
    keywords: ['coffee', 'drink', 'cup', 'mug', 'tea', 'cafe', 'hot', 'beverage'],
    icon: defineAsyncComponent(() => import('./CoffeeIcon.vue')),
    raw: () => import('./CoffeeIcon.vue?raw'),
  },
  {
    name: 'BookTextIcon',
    keywords: ['reading', 'booklet', 'magazine', 'leaflet', 'pamphlet', 'tome', 'library'],
    icon: defineAsyncComponent(() => import('./BookTextIcon.vue')),
    raw: () => import('./BookTextIcon.vue?raw'),
  },
  {
    name: 'AngryIcon',
    keywords: ['mad', 'upset', 'angry', 'furious', 'emotion', 'face'],
    icon: defineAsyncComponent(() => import('./AngryIcon.vue')),
    raw: () => import('./AngryIcon.vue?raw'),
  },
  {
    name: 'CircleCheckIcon',
    keywords: ['done', 'todo', 'tick', 'complete', 'task'],
    icon: defineAsyncComponent(() => import('./CircleCheckIcon.vue')),
    raw: () => import('./CircleCheckIcon.vue?raw'),
  },
  {
    name: 'ActivityIcon',
    keywords: [
      'pulse',
      'action',
      'motion/react',
      'movement',
      'exercise',
      'fitness',
      'healthcare',
      'heart rate monitor',
      'vital signs',
      'vitals',
      'emergency room',
      'er',
      'intensive care',
      'hospital',
      'defibrillator',
      'earthquake',
      'siesmic',
      'magnitude',
      'richter scale',
      'aftershock',
      'tremor',
      'shockwave',
      'audio',
      'waveform',
      'synthesizer',
      'synthesiser',
      'music',
    ],
    icon: defineAsyncComponent(() => import('./ActivityIcon.vue')),
    raw: () => import('./ActivityIcon.vue?raw'),
  },
  {
    name: 'AttachFileIcon',
    keywords: ['attachment', 'file'],
    icon: defineAsyncComponent(() => import('./AttachFileIcon.vue')),
    raw: () => import('./AttachFileIcon.vue?raw'),
  },
  {
    name: 'TrendingUpIcon',
    keywords: ['up', 'trend', 'graph', 'upward', 'increase', 'statistics'],
    icon: defineAsyncComponent(() => import('./TrendingUpIcon.vue')),
    raw: () => import('./TrendingUpIcon.vue?raw'),
  },
  {
    name: 'TrendingDownIcon',
    keywords: ['down', 'trend', 'graph', 'downward', 'decrease', 'statistics'],
    icon: defineAsyncComponent(() => import('./TrendingDownIcon.vue')),
    raw: () => import('./TrendingDownIcon.vue?raw'),
  },
  {
    name: 'TrendingUpDownIcon',
    keywords: [
      'up',
      'trend',
      'graph',
      'upward',
      'increase',
      'statistics',
      'down',
      'trend',
      'graph',
      'downward',
      'decrease',
    ],
    icon: defineAsyncComponent(() => import('./TrendingUpDownIcon.vue')),
    raw: () => import('./TrendingUpDownIcon.vue?raw'),
  },
  {
    name: 'AtSignIcon',
    keywords: ['mention', 'at', 'email', 'message', '@'],
    icon: defineAsyncComponent(() => import('./AtSignIcon.vue')),
    raw: () => import('./AtSignIcon.vue?raw'),
  },
  {
    name: 'SyringeIcon',
    keywords: ['medicine', 'medical', 'needle', 'pump', 'plunger', 'nozzle', 'blood'],
    icon: defineAsyncComponent(() => import('./SyringeIcon.vue')),
    raw: () => import('./SyringeIcon.vue?raw'),
  },
  {
    name: 'FlaskIcon',
    keywords: ['beaker', 'erlenmeyer', 'lab', 'chemistry', 'experiment', 'test'],
    icon: defineAsyncComponent(() => import('./FlaskIcon.vue')),
    raw: () => import('./FlaskIcon.vue?raw'),
  },
];
