// import __SearchIcon from './SearchIcon.vue';
// import __CartIcon from './CartIcon.vue';
// import __LayersIcon from './LayersIcon.vue';
// import __GripIcon from './GripIcon.vue';
// import __FrameIcon from './FrameIcon.vue';
// import __SunIcon from './SunIcon.vue';
// import __DeleteIcon from './DeleteIcon.vue';
// import __FileStackIcon from './FileStackIcon.vue';
// import __SettingGearIcon from './SettingGearIcon.vue';
// import __CalendarCogIcon from './CalendarCogIcon.vue';
// import __MenuIcon from './MenuIcon.vue';
// import __CopyIcon from './CopyIcon.vue';
// import __AudioLinesIcon from './AudioLinesIcon.vue';
// import __ArchiveIcon from './ArchiveIcon.vue';
// import __LogoutIcon from './LogoutIcon.vue';
// import __CircleHelpIcon from './CircleHelpIcon.vue';
// import __SquareStackIcon from './SquareStackIcon.vue';
// import __MessageCircleIcon from './MessageCircleIcon.vue';
// import __MessageCircleMoreIcon from './MessageCircleMoreIcon.vue';
// import __ArrowLeftIcon from './ArrowLeftIcon.vue';
// import __ArrowRightIcon from './ArrowRightIcon.vue';
// import __RefreshIcon from './RefreshIcon.vue';
// import __DownloadIcon from './DownloadIcon.vue';
// import __SquarePenIcon from './SquarePenIcon.vue';
// import __CursorClickIcon from './CursorClickIcon.vue';
// import __ClockIcon from './ClockIcon.vue';
// import __BadgeAlertIcon from './BadgeAlertIcon.vue';
// import __BadgePercentIcon from './BadgePercentIcon.vue';
// import __ChartPieIcon from './ChartPieIcon.vue';
// import __CompassIcon from './CompassIcon.vue';
// import __TimerIcon from './TimerIcon.vue';
// import __ExpandIcon from './ExpandIcon.vue';
// import __GaugeIcon from './GaugeIcon.vue';
// import __BoneIcon from './BoneIcon.vue';
// import __AlignCenterIcon from './AlignCenterIcon.vue';
// import __AlignHorizontalIcon from './AlignHorizontalIcon.vue';
// import __AlignVerticalIcon from './AlignVerticalIcon.vue';
// import __BellIcon from './BellIcon.vue';
// import __UpvoteIcon from './UpvoteIcon.vue';
// import __DownvoteIcon from './DownvoteIcon.vue';
// import __UsersIcon from './UsersIcon.vue';
// import __HandCoinsIcon from './HandCoinsIcon.vue';
// // 512 512
// import __SyringeIcon from './SyringeIcon.vue';
// import __FlaskIcon from './FlaskIcon.vue';

// export const SearchIcon = __SearchIcon;
// export const CartIcon = __CartIcon;
// export const LayersIcon = __LayersIcon;
// export const GripIcon = __GripIcon;
// export const FrameIcon = __FrameIcon;
// export const SunIcon = __SunIcon;
// export const DeleteIcon = __DeleteIcon;
// export const FileStackIcon = __FileStackIcon;
// export const SettingGearIcon = __SettingGearIcon;
// export const CalendarCogIcon = __CalendarCogIcon;
// export const MenuIcon = __MenuIcon;
// export const CopyIcon = __CopyIcon;
// export const AudioLinesIcon = __AudioLinesIcon;
// export const ArchiveIcon = __ArchiveIcon;
// export const LogoutIcon = __LogoutIcon;
// export const CircleHelpIcon = __CircleHelpIcon;
// export const SquareStackIcon = __SquareStackIcon;
// export const MessageCircleIcon = __MessageCircleIcon;
// export const MessageCircleMoreIcon = __MessageCircleMoreIcon;
// export const ArrowLeftIcon = __ArrowLeftIcon;
// export const ArrowRightIcon = __ArrowRightIcon;
// export const RefreshIcon = __RefreshIcon;
// export const DownloadIcon = __DownloadIcon;
// export const SquarePenIcon = __SquarePenIcon;
// export const CursorClickIcon = __CursorClickIcon;
// export const ClockIcon = __ClockIcon;
// export const BadgeAlertIcon = __BadgeAlertIcon;
// export const BadgePercentIcon = __BadgePercentIcon;
// export const ChartPieIcon = __ChartPieIcon;
// export const CompassIcon = __CompassIcon;
// export const TimerIcon = __TimerIcon;
// export const ExpandIcon = __ExpandIcon;
// export const GaugeIcon = __GaugeIcon;
// export const BoneIcon = __BoneIcon;
// export const AlignCenterIcon = __AlignCenterIcon;
// export const AlignHorizontalIcon = __AlignHorizontalIcon;
// export const AlignVerticalIcon = __AlignVerticalIcon;
// export const BellIcon = __BellIcon;
// export const UpvoteIcon = __UpvoteIcon;
// export const DownvoteIcon = __DownvoteIcon;
// export const UsersIcon = __UsersIcon;
// export const HandCoinsIcon = __HandCoinsIcon;
// export const SyringeIcon = __SyringeIcon;
// export const FlaskIcon = __FlaskIcon;
